# Hollowfang Trade — Set 2 card definitions
# Each key is a card name, mapped to a dictionary of its properties.
# Properties must match the fields defined in CardConfig.gd.
const SET_DEFINITIONS := {
	"Veilwing Spectre": {
		"Type": "Monster",
		"Cost": 2,
		"Attack": 3,
		"HP": 2,
		"Abilities": "Evasion: Cannot be targeted by single-target abilities.",
		"_Sprite": "res://assets/monsters/pack_02/Pixel Battlers - Animated RPG Monsters 02/TB_Monster_007/TB_Monster_007_A.png",
		"_FrameW": 64,
		"_FrameH": 64,
		"_FrameCount": 8,
		"_FPS": 8.0,
	},
	"Stoneback Golem": {
		"Type": "Monster",
		"Cost": 3,
		"Attack": 2,
		"HP": 7,
		"Abilities": "Sturdy: Reduce all incoming {damage} by 1.",
		"_Sprite": "res://assets/monsters/pack_02/Pixel Battlers - Animated RPG Monsters 02/TB_Monster_008/TB_Monster_008_A.png",
		"_FrameW": 64,
		"_FrameH": 64,
		"_FrameCount": 8,
		"_FPS": 8.0,
	},
	"Swampfang Drake": {
		"Type": "Monster",
		"Cost": 2,
		"Attack": 4,
		"HP": 2,
		"Abilities": "Poison: Deals 1 additional {damage} at the start of each turn.",
		"_Sprite": "res://assets/monsters/pack_02/Pixel Battlers - Animated RPG Monsters 02/TB_Monster_009/TB_Monster_009_A.png",
		"_FrameW": 64,
		"_FrameH": 64,
		"_FrameCount": 8,
		"_FPS": 8.0,
	},
	"Frostmantle Sprite2D": {
		"Type": "Monster",
		"Cost": 1,
		"Attack": 1,
		"HP": 3,
		"Abilities": "Chill: Enemies that attack this lose 1 Attack until end of turn.",
		"_Sprite": "res://assets/monsters/pack_02/Pixel Battlers - Animated RPG Monsters 02/TB_Monster_010/TB_Monster_010_A.png",
		"_FrameW": 64,
		"_FrameH": 64,
		"_FrameCount": 8,
		"_FPS": 8.0,
	},
	"Embercrest Chimera": {
		"Type": "Monster",
		"Cost": 5,
		"Attack": 6,
		"HP": 5,
		"Abilities": "Blaze: Deals {damage} to all enemies when this attacks.",
		"_Sprite": "res://assets/monsters/pack_02/Pixel Battlers - Animated RPG Monsters 02/TB_Monster_011/TB_Monster_011_A.png",
		"_FrameW": 64,
		"_FrameH": 64,
		"_FrameCount": 8,
		"_FPS": 8.0,
	},
}
